version: "3.7"

x-variables: &variables
  ENV_STAGE: local

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    volumes:
      - /path/to/your/project/on/vps:/usr/src/web/:cached
      - postgres_socket:/postgres_socket
    ports:
      - "8000:8000"
    environment:
      <<: *variables
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/dev/env/.mailhog.env
      - docker/prod/env/.data.env
    depends_on: [db, redis]
    restart: unless-stopped
    networks:
      - microservice_network
      - separated_network
    extra_hosts:
      - "gateway-host:66.29.139.175"
    healthcheck:
      test: curl --fail -s http://66.29.139.175:8000$$HEALTH_CHECK_URL || exit 1
      interval: 1m30s
      timeout: 3s