version: "3.7"

services:
  nginx:
    image: staticfloat/nginx-certbot
    container_name: nginx
    network_mode: host
    restart: "always"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./docker/prod/nginx/certbot.conf:/etc/nginx/user.conf.d/nginx_template.conf:ro
      - ./docker/prod/nginx/conf.d/proxy.conf:/etc/nginx/user.conf.d/proxy.conf:ro
    environment:
      CERTBOT_EMAIL: your@email.com
      # variable names are space-separated
      ENVSUBST_VARS: APP
      APP: backend.pandora-maining.kz

volumes:
  letsencrypt:
