# Generated by Django 3.2.16 on 2023-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='id платежа'),
        ),
    ]
