# Generated by Django 3.2.16 on 2023-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок депозита'),
        ),
    ]
