# Generated by Django 3.2.16 on 2023-01-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_deposit_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок депозита'),
        ),
    ]
