# Generated by Django 3.2.16 on 2023-01-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20230112_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction',
        ),
    ]
