# Generated by Django 3.2.16 on 2023-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction',
        ),
    ]
